# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'CallBlocka.xcodeproj'
platform :ios, '9.0'
target 'CallBlocka' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flikr
   # iPad mini / iPhoneX detection
   pod 'Device', '~> 3.0.0'
   pod 'Alamofire'
   #most widely-used auto-layout engine for ios
   pod 'SnapKit', '~> 4.0.0' 
   pod 'Material'
   pod 'CocoaLumberjack'
   pod 'CodableAlamofire'
   pod 'SDWebImage'

   pod 'LumberjackConsole'
   
   pod 'AWSCore', '~> 2.8.0'
   pod 'AWSCognitoIdentityProvider', '~> 2.8.0'
end
